apiVersion: batch/v1
kind: Job
metadata:
  name: ns-controller-post-install
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: ns-controller-post-install
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: ns-controller-controller-manager
      restartPolicy: Never
      containers:
      - name: ns-controller-post-install
        image: 192.168.33.16:5000/bitnami/kubectl:latest
        args: 
        - "label"
        - "namespace"
        - "ns-controller"
        - "--overwrite"
        - "ctrl=ns-controller"
