---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-controller-controller-manager
  namespace: ns-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-controller-leader-election
  namespace: ns-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-controller-leader-election
  namespace: ns-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-controller-leader-election
subjects:
  - kind: ServiceAccount
    name: ns-controller-controller-manager
    namespace: ns-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-generator
  namespace: ns-controller
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    resourceNames:
      - {{ .Values.webhookConfig.webhookNsName | quote }}
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-generator
subjects:
  - kind: ServiceAccount
    name: ns-controller-controller-manager
    namespace: ns-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-generator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ .Values.init.secretName }}
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-generator
  namespace: ns-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-generator
subjects:
  - kind: ServiceAccount
    name: ns-controller-controller-manager
    namespace: ns-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    resourceNames:
      - ns-controller
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-controller-manager
subjects:
  - kind: ServiceAccount
    name: ns-controller-controller-manager
    namespace: ns-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-controller-proxy
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-controller-proxy
subjects:
  - kind: ServiceAccount
    name: ns-controller-controller-manager
    namespace: ns-controller
