apiVersion: v1
kind: Service
metadata:
  name: ns-controller-webhook
  namespace: ns-controller
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ns-controller-controller-manager-metrics
  namespace: ns-controller
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
  type: ClusterIP
